#!/bin/bash

MAILDIR="${1:-$HOME/Mail}"
IGNORE="$2"
ENDL='
'

for account in "$MAILDIR"/*; do
    if [ -d "$account" ] && ! echo "$account" | grep -qE "${IGNORE:-IGNOREME}"; then
        mails="$(find "$account/INBOX/new" -type f | wc -l)"
        if [ "$mails" -gt 0 ]; then
            email="message"

            if [ "$mails" -gt 1 ]
            then
                email="messages"
            fi

            MESSAGE="${MESSAGE:+${MESSAGE}${ENDL}}$mails $email found in account $(basename "$account") inbox"
        fi
    fi
done

if [ -n "$MESSAGE" ]; then
    echo "$MESSAGE"

    . "$HOME"/.dbus/session-bus/*
    export DBUS_SESSION_BUS_ADDRESS DBUS_SESSION_BUS_PID DBUS_SESSION_BUS_WINDOWID

    /usr/bin/notify-send -t 10000 'New Mail' "$MESSAGE"
fi
