#!/bin/sh

jsonfile=/home/taylor/.forticonnect.json

while getopts j: opt
do
    case $opt in
        j) jsonfile="$OPTARG";;
        ?) exit 2;;
    esac
done

shift $(($OPTIND - 1))

username=$(jq -Mrc '.username' "$jsonfile")
server=$(jq -Mrc '.server' "$jsonfile")
port=$(jq -Mrc '.port' "$jsonfile")

exec /opt/forticlientsslvpn/forticlientsslvpn_cli --server "${server}:${port}" --vpnuser "$username"
